spring:
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: localhost:9200
            repositories:
                enabled: true
server:
    port: 6767