spring:
    application:
        name: search-service
    data:
        elasticsearch:
            cluster-name: elasticsearch
            cluster-nodes: localhost:9200
            repositories:
                enabled: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 0

